version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.11.2
    parallelism: 1
    working_directory: ~/kb
    steps:
      - checkout
      - attach_workspace:
          at: ~/kb
      - restore_cache:
          key: v1-yarn-{{ checksum "yarn.lock" }}
      - run: yarn install
      - save_cache:
          key: v1-yarn-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run: yarn run build
      - persist_to_workspace:
          root: .
          paths: docs
      - run: git commit -am "[skip ci]
      - run: git push -q https://github.com/actionitdev/knowledgebase.git master